"""
app.py
------
Streamlit dashboard for the Student Performance project.

What this app does:
    1. Shows the dataset and summary statistics.
    2. Displays the EDA plots generated by analysis.py.
    3. Lets the user enter a student's profile and predicts pass/fail
       using the trained Random Forest model.

Run:    streamlit run app.py
"""

import os
import pickle

import pandas as pd
import streamlit as st


# =============================================================================
# 1) PAGE CONFIG (must be the first Streamlit call)
# =============================================================================
st.set_page_config(
    page_title="Student Performance Predictor",
    page_icon="📚",
    layout="wide",
)


# =============================================================================
# 2) LOAD DATA AND TRAINED MODEL  (cached so they only load once)
# =============================================================================
# @st.cache_data tells Streamlit: "remember the result of this function so we
# don't reload the CSV every time the user changes a slider".
@st.cache_data
def load_data():
    return pd.read_csv("data/student-mat.csv", sep=";")


@st.cache_resource
def load_model():
    with open("model.pkl", "rb") as f:
        return pickle.load(f)


# Friendly error message if the user forgot to run analysis.py first.
if not os.path.exists("model.pkl") or not os.path.exists("data/student-mat.csv"):
    st.error(
        "⚠️ Setup not complete. Please run these commands first:\n\n"
        "```\npython download_data.py\npython analysis.py\n```"
    )
    st.stop()

df = load_data()
bundle = load_model()
model = bundle["model"]
feature_columns = bundle["columns"]


# =============================================================================
# 3) HEADER
# =============================================================================
st.title("📚 Student Performance Predictor")
st.markdown(
    "**Intro to Data Science — Semester Project (Fall 2025)**  \n"
    "Predicting whether a student will pass their final math exam "
    "using the UCI Student Performance dataset (395 Portuguese students)."
)


# =============================================================================
# 4) TABS — splits the page into 4 clean sections
# =============================================================================
tab_overview, tab_eda, tab_predict, tab_about = st.tabs(
    ["📊 Dataset Overview", "📈 Visualizations", "🎯 Predict", "ℹ️ About"]
)


# -----------------------------------------------------------------------------
# TAB 1: DATASET OVERVIEW
# -----------------------------------------------------------------------------
with tab_overview:
    st.header("Dataset Overview")

    # Top-level metrics
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Students", df.shape[0])
    col2.metric("Features", df.shape[1] - 1)
    col3.metric("Pass Rate", f"{(df['G3'] >= 10).mean() * 100:.1f}%")
    col4.metric("Avg Final Grade", f"{df['G3'].mean():.2f} / 20")

    st.subheader("First 10 rows")
    st.dataframe(df.head(10))

    st.subheader("Summary Statistics")
    st.dataframe(df.describe())

    with st.expander("ℹ️ What does each column mean?"):
        st.markdown("""
        - **school** — Student's school (GP = Gabriel Pereira, MS = Mousinho da Silveira)
        - **sex** — F (female) or M (male)
        - **age** — Age in years (15–22)
        - **address** — U (urban) or R (rural)
        - **studytime** — Weekly study time: 1 (<2h), 2 (2-5h), 3 (5-10h), 4 (>10h)
        - **failures** — Number of past class failures (0–3)
        - **absences** — Number of school absences (0–93)
        - **Medu / Fedu** — Mother's / Father's education (0 = none, 4 = higher education)
        - **goout** — Going out with friends (1 = very low, 5 = very high)
        - **Dalc / Walc** — Workday / Weekend alcohol consumption (1–5)
        - **health** — Current health (1 = very bad, 5 = very good)
        - **G1, G2, G3** — First period, second period, and **final** grades (0–20)
        """)


# -----------------------------------------------------------------------------
# TAB 2: VISUALIZATIONS (loads pre-saved PNG files from the plots/ folder)
# -----------------------------------------------------------------------------
with tab_eda:
    st.header("Exploratory Data Analysis")

    plot_files = [
        ("01_grade_distribution.png", "Distribution of Final Grades",
         "Most students score between 8 and 14. The red dashed line is the "
         "pass mark (10). About 1 in 3 students fails."),

        ("02_pass_fail_count.png", "Pass vs Fail Count",
         "Shows how many students pass vs fail in absolute numbers."),

        ("03_correlation_heatmap.png", "Correlation Heatmap",
         "Strong red squares show features that move together. Notice how "
         "G1 and G2 are extremely correlated with G3 (final grade)."),

        ("04_grade_by_studytime.png", "Final Grade vs Study Time",
         "**Insight:** Students who study more than 5 hours/week score noticeably higher."),

        ("05_grade_by_failures.png", "Final Grade vs Past Failures",
         "**Insight:** Students with past failures consistently underperform — the "
         "single biggest predictor of failing again."),

        ("06_absences_vs_grade.png", "Absences vs Final Grade",
         "**Insight:** Above ~25 absences, almost no student passes. Attendance matters."),

        ("07_grade_by_gender.png", "Final Grade by Gender",
         "Distribution is similar across genders, with male students slightly higher on average."),

        ("08_feature_importance.png", "Feature Importance (Random Forest)",
         "Which features the model relied on most to make predictions."),
    ]

    for filename, title, caption in plot_files:
        path = os.path.join("plots", filename)
        if os.path.exists(path):
            st.subheader(title)
            st.image(path, use_container_width=True)
            st.caption(caption)
            st.divider()
        else:
            st.warning(f"Missing plot: {filename}. Run `python analysis.py` first.")


# -----------------------------------------------------------------------------
# TAB 3: INTERACTIVE PREDICTION
# -----------------------------------------------------------------------------
with tab_predict:
    st.header("Predict Pass / Fail for a Student")
    st.markdown("Fill in the student's profile below — the model will predict the outcome.")

    # Two columns of inputs to keep the form compact.
    col_left, col_right = st.columns(2)

    with col_left:
        sex = st.radio("Sex", ["F", "M"], horizontal=True)
        age = st.slider("Age", 15, 22, 17)
        studytime = st.select_slider(
            "Weekly study time",
            options=[1, 2, 3, 4],
            value=2,
            format_func=lambda x: {1: "<2h", 2: "2–5h", 3: "5–10h", 4: ">10h"}[x],
        )
        failures = st.slider("Past class failures", 0, 3, 0)
        absences = st.slider("Absences", 0, 93, 4)
        internet = st.radio("Internet at home?", ["yes", "no"], horizontal=True)

    with col_right:
        Medu = st.slider("Mother's education (0=none, 4=higher)", 0, 4, 2)
        Fedu = st.slider("Father's education (0=none, 4=higher)", 0, 4, 2)
        goout = st.slider("Going out with friends (1=low, 5=very high)", 1, 5, 3)
        Dalc = st.slider("Workday alcohol (1=very low, 5=very high)", 1, 5, 1)
        Walc = st.slider("Weekend alcohol (1=very low, 5=very high)", 1, 5, 2)
        health = st.slider("Current health (1=very bad, 5=very good)", 1, 5, 4)

    # When the user clicks the button, build a one-row DataFrame and predict.
    if st.button("🎯 Predict", type="primary", use_container_width=True):
        # Build the input row with the SAME column order the model was trained on.
        # We start with raw values, then one-hot encode like in analysis.py.
        raw = pd.DataFrame([{
            "age": age,
            "studytime": studytime,
            "failures": failures,
            "absences": absences,
            "Medu": Medu,
            "Fedu": Fedu,
            "goout": goout,
            "Dalc": Dalc,
            "Walc": Walc,
            "health": health,
            "sex_M": 1 if sex == "M" else 0,
            "internet_yes": 1 if internet == "yes" else 0,
        }])

        # Make sure columns line up exactly with what the model expects.
        # Any missing column is filled with 0; extra columns are dropped.
        input_row = raw.reindex(columns=feature_columns, fill_value=0)

        # predict() -> 0 (fail) or 1 (pass)
        # predict_proba() -> probability of each class
        prediction = model.predict(input_row)[0]
        proba = model.predict_proba(input_row)[0]

        # Show the result with nice formatting.
        st.divider()
        if prediction == 1:
            st.success(f"### ✅ Predicted: PASS  \nConfidence: **{proba[1] * 100:.1f}%**")
        else:
            st.error(f"### ❌ Predicted: FAIL  \nConfidence: **{proba[0] * 100:.1f}%**")

        # Show the probability bar.
        st.markdown("**Probability breakdown:**")
        st.progress(float(proba[1]), text=f"Pass: {proba[1] * 100:.1f}%   |   Fail: {proba[0] * 100:.1f}%")


# -----------------------------------------------------------------------------
# TAB 4: ABOUT
# -----------------------------------------------------------------------------
with tab_about:
    st.header("About This Project")
    st.markdown("""
    **Course:** Introduction to Data Science (Fall 2025)
    **Project Type:** Data-Driven Insights Prototype
    **Domain:** Education Analytics
    **Dataset:** UCI Student Performance — 395 Portuguese students (math course)

    ### Pipeline
    1. **Data Collection** — Downloaded from the UCI Machine Learning Repository.
    2. **Cleaning** — Verified no missing values; types correctly inferred.
    3. **Feature Engineering** — Created binary target `passed = (G3 >= 10)`.
    4. **EDA** — 7 visualizations highlighting study time, failures, and absences as key drivers.
    5. **Modeling** — Compared Logistic Regression, Decision Tree, Random Forest.
    6. **Evaluation** — Used accuracy, confusion matrix, and classification report.
    7. **Deployment** — This Streamlit dashboard.

    ### Libraries Used
    - **pandas** — Data manipulation
    - **numpy** — Numerical operations
    - **matplotlib + seaborn** — Visualizations
    - **scikit-learn** — Machine learning models and metrics
    - **streamlit** — Interactive web dashboard
    """)
